### ISSUE TITLE
Class 'Kirby' not found in after Update to Kirby 3.0.3

### ISSUE THREAD

**Issue by schnti** [sylvainjule/kirby-imageradio#6] opened 2019-03-07 12:53 UTC
Fatal error: Uncaught Error: Class 'Kirby' not found in .../vendor/sylvainjule/imageradio/config.php:3 Stack trace: #0 .../vendor/composer/autoload_real.php(66): require() #1 .../vendor/composer/autoload_real.php(56): composerRequiref500705cbefda5b7501a96695f683400('490010e42a89d95...', '/Users/tschneid...') #2 .../vendor/autoload.php(7): ComposerAutoloaderInitf500705cbefda5b7501a96695f683400::getLoader() #3 .../website/kirby/bootstrap.php(18): include('/Users/tschneid...') #4 .../website/index.php(3): require('/Users/tschneid...') #5 {main} thrown in .../vendor/sylvainjule/imageradio/config.php on line 3

**Comment by sylvainjule** [comment] 2019-03-17 16:42
Does the latest release fix your issue?

**Comment by sylvainjule** [comment] 2019-03-31 09:01
@schnti I'm closing the issue since the missing `Kirby` class is probably not due to the plugin itself. I cannot reproduce. Please feel free to reopen if needed.

**Closed by sylvainjule** 2019-03-31 09:01 UTC
Labels: bug, needs: information
