### ISSUE TITLE
imageradio in Blocks

### ISSUE THREAD

**Issue by AlexanderBoenninger** [sylvainjule/kirby-imageradio#16] opened 2022-07-15 09:00 UTC
Hey. 

Thanks for this very helpful Plugin!

There seems to be a Problem with using it in Kirby Blocks. It simply gets not recognized as a radio field. In this case, I had to switch to the normal radio field.

Maybe you have an idea to fix this and make your plugin even more powerful.

**Comment by sylvainjule** [comment] 2023-11-14 09:58
I cannot reproduce, it is working nicely on my end since 3.5 up to 3.9. So I'm closing this, but if the issue still happens for you don't hesitate to open a new issue with details about your versions / setup.

**Closed by sylvainjule** 2023-11-14 09:58 UTC
Labels: bug
